### ISSUE TITLE
Error in checkAssays2Txps(assays, txps) : none of the transcripts in the quantification files are in the GTF

### ISSUE THREAD

**Issue by csgroen** [mikelove/tximeta#57] opened 2021-05-04 07:54 UTC
I'm having some trouble importing some data pre-processed with Salmon Alevin into R using `tximeta`.

For pre-processing, I've used `salmon 1.4.0` with a salmon index made following [these instructions](https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/) using Gencode v37.

Currently, I'm using `makeLinkedTxome` with the GTF I downloaded from Gencode along with the transcripts and genome to generate the salmon index.

**I've tried:**
1. letting `tximeta` identify the transcriptome (transcriptome is identified correctly, but import fails with the same error), 
2. setting `skipMeta = TRUE` and passing `tx2gene` with the `tx2gene.tsv` file I used for Salmon (`tgMap`)

I also get multiple instances of the same _warning_:
```
In Matrix::sparseMatrix(i = unlist(gene.idx), j = cell.idx,  ... :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
```
Any help would be appreciated.

**Comment by mikelove** [comment] 2021-05-04 10:05
Is there more to the error? Does it give examples of the names of txps?

Can you manually look at the names of txps in the quant.sf and in the GTF you are providing?

**Comment by csgroen** [comment] 2021-05-04 15:22
It doesn't give me any txps as example when the error occurs.
I don't have a `quant.sf` file as it's Alevin not Salmon (only a `quants_mat.gz`). It's a binary and I can't take a look at it.

I ran traceback, this is what I get:
```
3: stop("none of the transcripts in the quantification files are in the GTF")
2: checkAssays2Txps(assays, txps)
1: tximeta("pp_alevin/alevin/quants_mat.gz", type = "alevin", useHub = FALSE)
```
so not very helpful.

If I try importing with *tximport*, however, the import is successful (with the same warning I reported above) using the `tx2gene.tsv` I provided when running salmon.

I built `tx2gene.tsv` with `plyranges`:

```
library(plyranges)
gencode37 <- read_gff("reference/gencode.v37.annotation.gtf.gz")
gencode37 %>%
    as_tibble() %>%
    select(transcript_id, gene_name) %>%
    write_tsv("reference/tx2gene.tsv", col_names = FALSE)
```

**Comment by mikelove** [comment] 2021-05-04 15:47
Thanks for the report.

Looks like there are definitely a couple of issues:

1. the hash should be identical to one in tximeta (that is, if you are using tximeta version >= 1.8.4)
2. don't know why this works for tximport but not for tximeta

Would it be possible for you to `tar -czf` the entire alevin output? That is: tar the directory with all the output of Salmon, not just the `alevin` sub-directory. And then you can share with an email to maintainer("tximeta")? I'll take a look ASAP and loop back here.

In the meantime, if you have tximport, you can manually construct a SE or SCE.

The warning above is fixed in the devel branch of fishpond, which will be pushed out as release with the new Bioc release in a few days.

**Comment by csgroen** [comment] 2021-05-04 18:15
Thanks, e-mail sent.

I have the current devel version of tximeta, but the release version of fishpond.

**Comment by mikelove** [comment] 2021-05-06 11:17
The quantification data has gene symbols instead of Ensembl IDs ("ENSG00000..."). 

tximeta is designed to do all the processing for you, but for GENCODE and Ensembl, it's built around using ENST and ENSG. These are better rownames anyway than the gene symbols, as there are many genes that do not have an assigned symbol, and sometimes multiple ENSG with more than one gene symbol.

So you can have the tximeta pipeline work out of the box (no need for linkedTxome) and also I think have better reproducibility of the quantification data by using a tx2gene file with Alevin that has Ensembl gene IDs instead of symbols. Once you have imported into R you can use tximeta's `addIds` to add symbols to the `mcols(se)` and then change the rownames as you like.

**Comment by mikelove** [comment] 2021-05-08 11:07
I've added a note to the vignette to make it clear that gene IDs are required as input to `tgMap` and not gene symbols: ee05abf

Thanks again for you post, I think this addresses the bug, so I'm closing the issue, but feel free to re-open if you have further difficulties.

**Closed by mikelove** 2021-05-08 11:07 UTC
